const wilayasCommunes = {
  "01-Adrar": {
    zone: 4,
    communes: {
      adrar: {},
      Akabli: { expressOnly: true },
      Aougrout: { expressOnly: true },
      Aoulef: { expressOnly: true },
      Bouda: { expressOnly: true },
      charouine: { expressOnly: true },
      Deldoul: { expressOnly: true },
      Fenoughil: { expressOnly: true },
      "In Zghmir": { expressOnly: true },
      "Ksar Kaddour": { expressOnly: true },
      Metarfa: { expressOnly: true },
      "Ouled Ahmed Tammi": { expressOnly: true },
      "Ouled Aïssa": { expressOnly: true },
      "Ouled Saïd ": { expressOnly: true },
      Reggane: { expressOnly: true },
      Sali: { expressOnly: true },
      Sebaa: { expressOnly: true },
      Talmine: { expressOnly: true },
      Tamantit: { expressOnly: true },
      Tamekten: { expressOnly: true },
      Tamest: { expressOnly: true },
      timimoun: {},
      Tinerkouk: { expressOnly: true },
      tit: { expressOnly: true },
      Tsabit: { expressOnly: true },
      "Zaouiet Kounta": { expressOnly: true },
    },
  },
  "02-Chlef": {
    zone: 2,
    communes: {
      "Abou El Hassan": { horsZone: 1, expressOnly: true },
      "aïn merane": { horsZone: 1, expressOnly: true },
      bénairia: { horsZone: 1, expressOnly: true },
      "béni bouateb": { horsZone: 1, expressOnly: true },
      "béni haoua": { horsZone: 1, expressOnly: true },
      "béni Rached": { horsZone: 1, expressOnly: true },
      boukadir: { horsZone: 1, expressOnly: true },
      Bouzeghaia: { horsZone: 1, expressOnly: true },
      breira: { horsZone: 1, expressOnly: true },
      Chettia: { horsZone: 1, expressOnly: true },
      chlef: {},
      dahra: { horsZone: 2, expressOnly: true },
      "el hadjadj": { horsZone: 2, expressOnly: true },
      "el karimia": { horsZone: 2, expressOnly: true },
      "El Marsa": { horsZone: 1, expressOnly: true },
      harchoun: { horsZone: 1, expressOnly: true },
      Harenfa: { horsZone: 2, expressOnly: true },
      "labiod medjadja": { horsZone: 1, expressOnly: true },
      moussadek: { horsZone: 2, expressOnly: true },
      "oued fodda": { horsZone: 1, expressOnly: true },
      "Oued Goussine": { horsZone: 2, expressOnly: true },
      "Oued Sly": { horsZone: 1, expressOnly: true },
      "ouled abbes": { horsZone: 1, expressOnly: true },
      "ouled fares": { horsZone: 1, expressOnly: true },
      "ouled ben abdelkader": { horsZone: 1, expressOnly: true },
      "Oum Drou": { horsZone: 1, expressOnly: true },
      sendjas: { horsZone: 1, expressOnly: true },
      "sidi akacha": { horsZone: 1, expressOnly: true },
      "sidi abderrahmane": { horsZone: 2, expressOnly: true },
      sobha: { horsZone: 1, expressOnly: true },
      Tadjena: { horsZone: 1, expressOnly: true },
      Talassa: { horsZone: 1, expressOnly: true },
      taougrit: { horsZone: 1, expressOnly: true },
      ténès: {},
      zerioua: { horsZone: 1, expressOnly: true },
    },
  },
  "03-Laghouat": {
    zone: 3,
    communes: {
      "Aïn Madhi": { expressOnly: true },
      "Bennasser Benchohra": { expressOnly: true },
      "El Assafia": { expressOnly: true },
      "El Ghicha": { expressOnly: true },
      "El Houaita": { expressOnly: true },
      "Gueltat Sidi Saad": { expressOnly: true },
      "Hassi Delaa": { expressOnly: true },
      "Hassi R'Mel": { expressOnly: true },
      Kheneg: { expressOnly: true },
      "Ksar El Hirane": { expressOnly: true },
      Laghouat: {},
      "Oued M'Zi": { expressOnly: true },
      "Sidi Makhlouf": { expressOnly: true },
      Tadjemout: { expressOnly: true },
    },
  },
  "04-Oum el bouaghi": {
    zone: 2,
    communes: {
      "Aïn Beïda": { expressOnly: true },
      "Aïn Diss": { expressOnly: true },
      "Aïn Fakroun": { expressOnly: true },
      "Aïn Kercha": { expressOnly: true },
      "Aïn M'lila": {},
      "Aïn Zitoun": { expressOnly: true },
      "Behir Chergui": { expressOnly: true },
      Berriche: { expressOnly: true },
      "Bir Chouhada": { expressOnly: true },
      Dhalaa: { expressOnly: true },
      "El Amiria": { expressOnly: true },
      "El Belala": { expressOnly: true },
      "El Djazia": { expressOnly: true },
      "El Fedjoudj Boughrara Saoudi": { expressOnly: true },
      "El Harmilia": { expressOnly: true },
      Fkirina: { expressOnly: true },
      "Hanchir Toumghani": { expressOnly: true },
      "Ksar Sbahi": { expressOnly: true },
      Meskiana: { expressOnly: true },
      "Oued Nini": { expressOnly: true },
      "Ouled Gacem": { expressOnly: true },
      "Ouled Hamla": { expressOnly: true },
      "Ouled Zouaï": { expressOnly: true },
      "Oum el Bouaghi": {},
      Rahia: { expressOnly: true },
      Sigus: { expressOnly: true },
      "Souk Naamane": { expressOnly: true },
      Zorg: { expressOnly: true },
    },
  },
  "05-Batna": {
    zone: 2,
    communes: {
      "Aïn Djasser": { expressOnly: true },
      "Aïn Touta": { expressOnly: true },
      "Aïn Yagout": { expressOnly: true },
      Arris: { expressOnly: true },
      Barika: {},
      Batna: {},
      "Ben Foudhala El Hakania": { expressOnly: true },
      Bitam: { expressOnly: true },
      Boulhilat: { expressOnly: true },
      Boumagueur: { expressOnly: true },
      "Boumia (Batna)": { expressOnly: true },
      Bouzina: { expressOnly: true },
      Chemora: { expressOnly: true },
      Chir: { expressOnly: true },
      Djerma: { expressOnly: true },
      Djezar: { expressOnly: true },
      "El Hassi": { expressOnly: true },
      "El Madher": { expressOnly: true },
      Fesdis: { expressOnly: true },
      "Foum Toub": { expressOnly: true },
      Ghassira: { expressOnly: true },
      Guigba: { expressOnly: true },
      Hidoussa: { expressOnly: true },
      Ichmoul: { expressOnly: true },
      Inoughissen: { expressOnly: true },
      Kimmel: { expressOnly: true },
      "Ksar Bellezma": { expressOnly: true },
      Lazrou: { expressOnly: true },
      Lemsane: { expressOnly: true },
      "M'doukel": { expressOnly: true },
      Maafa: { expressOnly: true },
      Menaa: { expressOnly: true },
      Merouana: { expressOnly: true },
      "N'Gaous": { expressOnly: true },
      "Oued Chaaba": { expressOnly: true },
      "Oued El Ma": { expressOnly: true },
      "Oued Taga": { expressOnly: true },
      "Ouled Aouf": { expressOnly: true },
      "Ouled Fadel": { expressOnly: true },
      "Ouled Sellam": { expressOnly: true },
      "Ouled Si Slimane": { expressOnly: true },
      "Ouyoun El Assafir": { expressOnly: true },
      Rahbat: { expressOnly: true },
      "Ras El Aioun": { expressOnly: true },
      Sefiane: { expressOnly: true },
      Seggana: { expressOnly: true },
      Seriana: { expressOnly: true },
      "T'Kout": { expressOnly: true },
      Talkhamt: { expressOnly: true },
      Taxlent: { expressOnly: true },
      Tazoult: { expressOnly: true },
      "Teniet El Abed": { expressOnly: true },
      Tighanimine: { expressOnly: true },
      Tigherghar: { expressOnly: true },
      Tilatou: { expressOnly: true },
      Timgad: { expressOnly: true },
      "Zanat El Beida": { expressOnly: true },
    },
  },
  "06-Bejaia": {
    zone: 2,
    communes: {
      "Ait Djellil": { expressOnly: true },
      "Aït Ksila": { expressOnly: true },
      "Aït Maouche": { expressOnly: true },
      "Aït Mellikeche": { expressOnly: true },
      "Aït R'zine": { expressOnly: true },
      "Aït Smail": { expressOnly: true },
      Akbou: {},
      Akfadou: { expressOnly: true },
      Amalou: { expressOnly: true },
      Amizour: { expressOnly: true },
      Aokas: { expressOnly: true },
      Barbacha: { expressOnly: true },
      Béjaïa: {},
      Boudjellil: { expressOnly: true },
      Bouhamza: { expressOnly: true },
      Boukhelifa: { expressOnly: true },
      Chellata: { expressOnly: true },
      Chemini: { expressOnly: true },
      Darguina: { expressOnly: true },
      "Draâ El Kaïd": { expressOnly: true },
      "El Kseur": {},
      "Fenaïa Ilmaten": { expressOnly: true },
      Ferraoun: { expressOnly: true },
      "Ighil Ali": { expressOnly: true },
      Ighram: { expressOnly: true },
      Kendira: { expressOnly: true },
      Kherrata: { expressOnly: true },
      Leflaye: { expressOnly: true },
      "M'cisna": { expressOnly: true },
      Melbou: { expressOnly: true },
      "Oued Ghir": { expressOnly: true },
      Ouzellaguen: { expressOnly: true },
      Seddouk: { expressOnly: true },
      Semaoun: { expressOnly: true },
      "Sidi Aïch": { expressOnly: true },
      "Sidi Ayad": { expressOnly: true },
      "Souk El Ténine": { expressOnly: true },
      "Souk Oufella": { expressOnly: true },
      "Tala Hamza": { expressOnly: true },
      Tamridjet: { expressOnly: true },
      "Taourirt Ighil": { expressOnly: true },
      Taskriout: { expressOnly: true },
      Tazmalt: { expressOnly: true },
      Tibane: { expressOnly: true },
      Tichy: { expressOnly: true },
      Tifra: { expressOnly: true },
      Timezrit: { expressOnly: true },
      Tinabdher: { expressOnly: true },
      Toudja: { expressOnly: true },
    },
  },
  "31-Oran": {
    zone: 0,
    communes: {
      "Aïn El Kerma": { expressOnly: true },
      "Aïn El Turk": { expressOnly: true },
      Arzew: {},
      "Ben Freha": { expressOnly: true },
      Bethioua: { expressOnly: true },
      "Bir El Djir": {},
      "Bou Sfer": { expressOnly: true },
      Boufatis: { expressOnly: true },
      Boutlelis: { expressOnly: true },
      "El Ançor": { expressOnly: true },
      "El Braya": { expressOnly: true },
      "El Kerma": { expressOnly: true },
      "Es Senia": { expressOnly: true },
      Gdyel: { expressOnly: true },
      "Hassi Ben Okba": { expressOnly: true },
      "Hassi Bounif": { expressOnly: true },
      "Hassi Mefsoukh": { expressOnly: true },
      "Marsat El Hadjadj": { expressOnly: true },
      "Mers El Kébir": { expressOnly: true },
      Misserghin: { expressOnly: true },
      Oran: {},
      "Oued Tlelat": { expressOnly: true },
      "Sidi Benyebka": { expressOnly: true },
      "Sidi Chami": { expressOnly: true },
      Tafraoui: { expressOnly: true },
    },
  },
};
