const wilayasCommunes = {
    adrar: {
        zone: 4,
        communes: {
            adrar: {  },
            Akabli: { expressOnly: true },
            "Aougrout": { expressOnly: true },
            Aoulef: { expressOnly: true },
            Bouda: { expressOnly: true },
            charouine: { expressOnly: true },
            Deldoul: { expressOnly: true },
            Fenoughil: { expressOnly: true },
            "In Zghmir": { expressOnly: true },
            "Ksar Kaddour": { expressOnly: true },
            Metarfa: { expressOnly: true },
            "Ouled Ahmed Tammi": { expressOnly: true },
            "Ouled Aïssa": { expressOnly: true },
            "Ouled Saïd ": { expressOnly: true },
            Reggane: { expressOnly: true },
            Sali: { expressOnly: true },
            Sebaa: { expressOnly: true },
            Talmine: { expressOnly: true },
            Tamantit: { expressOnly: true },
            Tamekten: { expressOnly: true },
            Tamest: { expressOnly: true },
            timimoun: { },
            "Tinerkouk": { expressOnly: true },
            tit: { expressOnly: true },
            Tsabit: { expressOnly: true },
            "Zaouiet Kounta": { expressOnly: true },
        },
    },
    chlef: {
        zone: 2,
        communes: {
            "Abou El Hassan": { horsZone: 1, expressOnly: true },
            "aïn merane": { horsZone: 1, expressOnly: true },
            bénairia: { horsZone: 1, expressOnly: true },
            "béni bouateb": { horsZone: 1, expressOnly: true },
            "béni haoua": { horsZone: 1, expressOnly: true },
			"béni Rached": { horsZone: 1, expressOnly: true },
            boukadir: { horsZone: 1, expressOnly: true },
			Bouzeghaia: { horsZone: 1, expressOnly: true },
            breira: { horsZone: 1, expressOnly: true },
			Chettia: { horsZone: 1, expressOnly: true },
            chlef: {},
            dahra: { horsZone: 2, expressOnly: true },
            "el hadjadj": { horsZone: 2, expressOnly: true }, 
            "el karimia": { horsZone: 2, expressOnly: true },
			"El Marsa": { horsZone: 1, expressOnly: true },
            harchoun: { horsZone: 1, expressOnly: true },
			"Harenfa": { horsZone: 2, expressOnly: true },
            "labiod medjadja": { horsZone: 1, expressOnly: true },
            moussadek: { horsZone: 2, expressOnly: true },
            "oued fodda": { horsZone: 1, expressOnly: true },
			"Oued Goussine": { horsZone: 2, expressOnly: true },
			"Oued Sly": { horsZone: 1, expressOnly: true },
            "ouled abbes": { horsZone: 1, expressOnly: true },
            "ouled fares": { horsZone: 1, expressOnly: true },
            "ouled ben abdelkader": { horsZone: 1, expressOnly: true },
			"Oum Drou": { horsZone: 1, expressOnly: true },
            sendjas: { horsZone: 1, expressOnly: true },
            "sidi akacha": { horsZone: 1, expressOnly: true },
            "sidi abderrahmane": { horsZone: 2, expressOnly: true },
            sobha: { horsZone: 1, expressOnly: true },
			Tadjena: { horsZone: 1, expressOnly: true },
			Talassa: { horsZone: 1, expressOnly: true },
            taougrit: { horsZone: 1, expressOnly: true },
            ténès: {},
            zerioua: { horsZone: 1, expressOnly: true },
        },
    },
    laghouat: {
        zone: 3,
        communes: {
      "Aïn Madhi": { expressOnly: true },
      "Bennasser Benchohra": { expressOnly: true },
      "El Assafia": { expressOnly: true },
      "El Ghicha": { expressOnly: true },
      "El Houaita": { expressOnly: true },
      "Gueltat Sidi Saad": { expressOnly: true },
      "Hassi Delaa": { expressOnly: true },
      "Hassi R'Mel": { expressOnly: true },
      Kheneg: { expressOnly: true },
      "Ksar El Hirane": { expressOnly: true },
      Laghouat: {},
      "Oued M'Zi": { expressOnly: true },
      "Sidi Makhlouf": { expressOnly: true },
      Tadjemout: { expressOnly: true },
        },
    },
    "oum el bouaghi": {
        zone: 2,
        communes: {
      "Aïn Beïda": { expressOnly: true },
      "Aïn Diss": { expressOnly: true },
      "Aïn Fakroun": { expressOnly: true },
      "Aïn Kercha": { expressOnly: true },
      "Aïn M'lila": {},
      "Aïn Zitoun": { expressOnly: true },
      "Behir Chergui": { expressOnly: true },
      Berriche: { expressOnly: true },
      "Bir Chouhada": { expressOnly: true },
      Dhalaa: { expressOnly: true },
      "El Amiria": { expressOnly: true },
      "El Belala": { expressOnly: true },
      "El Djazia": { expressOnly: true },
      "El Fedjoudj Boughrara Saoudi": { expressOnly: true },
      "El Harmilia": { expressOnly: true },
      Fkirina: { expressOnly: true },
      "Hanchir Toumghani": { expressOnly: true },
      "Ksar Sbahi": { expressOnly: true },
      Meskiana: { expressOnly: true },
      "Oued Nini": { expressOnly: true },
      "Ouled Gacem": { expressOnly: true },
      "Ouled Hamla": { expressOnly: true },
      "Ouled Zouaï": { expressOnly: true },
      "Oum el Bouaghi": {},
      Rahia: { expressOnly: true },
      Sigus: { expressOnly: true },
      "Souk Naamane": { expressOnly: true },
      Zorg: { expressOnly: true },
        },
    },
	oran: {
    zone: 0,
    communes: {
      "Aïn El Kerma": { expressOnly: true },
      "Aïn El Turk": { expressOnly: true },
      Arzew: {},
      "Ben Freha": { expressOnly: true },
      Bethioua: { expressOnly: true },
      "Bir El Djir": {},
      "Bou Sfer": { expressOnly: true },
      Boufatis: { expressOnly: true },
      Boutlelis: { expressOnly: true },
      "El Ançor": { expressOnly: true },
      "El Braya": { expressOnly: true },
      "El Kerma": { expressOnly: true },
      "Es Senia": { expressOnly: true },
      Gdyel: { expressOnly: true },
      "Hassi Ben Okba": { expressOnly: true },
      "Hassi Bounif": { expressOnly: true },
      "Hassi Mefsoukh": { expressOnly: true },
      "Marsat El Hadjadj": { expressOnly: true },
      "Mers El Kébir": { expressOnly: true },
      Misserghin: { expressOnly: true },
      Oran: {},
      "Oued Tlelat": { expressOnly: true },
      "Sidi Benyebka": { expressOnly: true },
      "Sidi Chami": { expressOnly: true },
      Tafraoui: { expressOnly: true },
    },
  },
};
