// ==========================================
// ZR EXPRESS (58 Wilayas) - Départ : Oran
// ==========================================
window.DATA_LIVRAISON = {
    1: { name: "Adrar", home: 950, desk: 550, desk_communes: ["Adrar"], communes: ["Adrar", "Reggane", "Timimoun", "Aoulef"] },
    2: { name: "Chlef", home: 550, desk: 300, desk_communes: ["Chlef", "Ténès"], communes: ["Chlef", "Ténès", "Boukadir", "Oued Sly", "Sendjas", "Oued Fodda"] },
    3: { name: "Laghouat", home: 750, desk: 400, desk_communes: ["Laghouat"], communes: ["Laghouat", "Aflou", "Hassi R'Mel"] },
    4: { name: "Oum El Bouaghi", home: 650, desk: 400, desk_communes: ["Oum El Bouaghi", "Aïn Beïda"], communes: ["Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Ain Fakroun"] },
    5: { name: "Batna", home: 650, desk: 400, desk_communes: ["Batna", "Barika"], communes: ["Batna", "Barika", "Ain Touta", "Merouana", "Tazoult"] },
    6: { name: "Béjaïa", home: 650, desk: 400, desk_communes: ["Béjaïa", "Akbou"], communes: ["Béjaïa", "Amizour", "El Kseur", "Akbou", "Sidi Aïch", "Tichy"] },
    7: { name: "Biskra", home: 750, desk: 400, desk_communes: ["Biskra"], communes: ["Biskra", "Tolga", "Sidi Okba"] },
    8: { name: "Béchar", home: 850, desk: 500, desk_communes: ["Béchar"], communes: ["Béchar", "Kenadsa", "Abadla"] },
    9: { name: "Blida", home: 500, desk: 300, desk_communes: ["Blida", "Boufarik"], communes: ["Blida", "Boufarik", "El Affroun", "Mouzaïa", "Bougara", "Larbaa", "Oued Alleug"] },
    10: { name: "Bouira", home: 600, desk: 350, desk_communes: ["Bouira", "Lakhdaria"], communes: ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Aïn Bessem", "M'Chedallah"] },
    11: { name: "Tamanrasset", home: 1150, desk: 700, desk_communes: ["Tamanrasset"], communes: ["Tamanrasset", "In Salah"] },
    12: { name: "Tébessa", home: 700, desk: 400, desk_communes: ["Tébessa"], communes: ["Tébessa", "Bir El Ater", "Cheria", "Ouenza"] },
    13: { name: "Tlemcen", home: 450, desk: 250, desk_communes: ["Tlemcen", "Maghnia", "Remchi"], communes: ["Tlemcen", "Mansourah", "Chetouane", "Remchi", "Maghnia", "Ghazaouet", "Nedroma", "Sebdou", "Hennaya"] },
    14: { name: "Tiaret", home: 550, desk: 300, desk_communes: ["Tiaret"], communes: ["Tiaret", "Frenda", "Sougueur", "Ksar Chellala"] },
    15: { name: "Tizi Ouzou", home: 600, desk: 350, desk_communes: ["Tizi Ouzou", "Azazga"], communes: ["Tizi Ouzou", "Aïn El Hammam", "Azazga", "Draâ Ben Khedda", "Tigzirt", "Boghni"] },
    16: { name: "Alger", home: 500, desk: 350, desk_communes: ["Alger Centre", "Kouba", "Dar El Beïda", "Bab Ezzouar", "Dely Ibrahim", "Rouïba", "Draria"], communes: ["Alger Centre", "Sidi M'Hamed", "Belouizdad", "Bab El Oued", "Bir Mourad Raïs", "El Biar", "Bouzaréah", "Birkhadem", "El Harrach", "Baraki", "Hussein Dey", "Kouba", "Dar El Beïda", "Bab Ezzouar", "Ben Aknoun", "Dely Ibrahim", "Hydra", "Mohammadia", "Bordj El Kiffan", "Birtouta", "Zéralda", "Rouïba", "Reghaïa"] },
    17: { name: "Djelfa", home: 650, desk: 350, desk_communes: ["Djelfa"], communes: ["Djelfa", "Ain Oussera", "Messaad", "Hassi Bahbah"] },
    18: { name: "Jijel", home: 650, desk: 400, desk_communes: ["Jijel", "Taher"], communes: ["Jijel", "El Aouana", "Taher", "El Milia"] },
    19: { name: "Sétif", home: 600, desk: 350, desk_communes: ["Sétif", "El Eulma"], communes: ["Sétif", "El Eulma", "Ain Oulmene", "Ain El Kebira", "Bougaa"] },
    20: { name: "Saïda", home: 500, desk: 300, desk_communes: ["Saïda"], communes: ["Saïda", "Ain El Hadjar", "Youb"] },
    21: { name: "Skikda", home: 650, desk: 400, desk_communes: ["Skikda"], communes: ["Skikda", "El Harrouch", "Azzaba", "Collo"] },
    22: { name: "Sidi Bel Abbès", home: 400, desk: 200, desk_communes: ["Sidi Bel Abbès", "Telagh"], communes: ["Sidi Bel Abbès", "Tessala", "Sfisef", "Telagh", "Ben Badis"] },
    23: { name: "Annaba", home: 700, desk: 400, desk_communes: ["Annaba", "El Bouni"], communes: ["Annaba", "El Bouni", "El Hadjar", "Berrahal"] },
    24: { name: "Guelma", home: 700, desk: 400, desk_communes: ["Guelma"], communes: ["Guelma", "Oued Zenati", "Bouchegouf"] },
    25: { name: "Constantine", home: 650, desk: 400, desk_communes: ["Constantine", "El Khroub"], communes: ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Aïn Smara"] },
    26: { name: "Médéa", home: 600, desk: 350, desk_communes: ["Médéa"], communes: ["Médéa", "Berrouaghia", "Ksar El Boukhari"] },
    27: { name: "Mostaganem", home: 400, desk: 200, desk_communes: ["Mostaganem"], communes: ["Mostaganem", "Aïn Tedeles", "Sidi Ali", "Hassi Mameche", "Mazagran"] },
    28: { name: "M'Sila", home: 650, desk: 350, desk_communes: ["M'Sila", "Bou Saâda"], communes: ["M'Sila", "Bou Saâda", "Sidi Aïssa"] },
    29: { name: "Mascara", home: 400, desk: 200, desk_communes: ["Mascara", "Sig"], communes: ["Mascara", "Sig", "Mohammadia", "Tighennif"] },
    30: { name: "Ouargla", home: 800, desk: 450, desk_communes: ["Ouargla", "Hassi Messaoud"], communes: ["Ouargla", "Hassi Messaoud", "Rouissat"] },
    31: { name: "Oran", home: 350, desk: 200, desk_communes: ["Oran", "Bir El Djir", "Es Senia"], communes: ["Oran", "Gdyel", "Bir El Djir", "Hassi Bounif", "Es Senia", "Arzew", "Bethioua", "Aïn El Turk", "El Kerma", "Sidi Chami", "Boutlelis", "Messerghin"] },
    32: { name: "El Bayadh", home: 750, desk: 450, desk_communes: ["El Bayadh"], communes: ["El Bayadh", "Brezina", "El Abiodh Sidi Cheikh"] },
    33: { name: "Illizi", home: 1150, desk: 700, desk_communes: ["Illizi"], communes: ["Illizi", "In Amenas"] },
    34: { name: "Bordj Bou Arreridj", home: 600, desk: 350, desk_communes: ["Bordj Bou Arreridj"], communes: ["Bordj Bou Arreridj", "Ras El Oued", "Mansoura"] },
    35: { name: "Boumerdès", home: 550, desk: 300, desk_communes: ["Boumerdès", "Khemis El Khechna"], communes: ["Boumerdès", "Bordj Menaïel", "Dellys", "Khemis El Khechna", "Isser", "Boudouaou"] },
    36: { name: "El Tarf", home: 700, desk: 400, desk_communes: ["El Tarf"], communes: ["El Tarf", "El Kala", "Ben M'Hidi", "Dréan"] },
    37: { name: "Tindouf", home: 1150, desk: 700, desk_communes: ["Tindouf"], communes: ["Tindouf"] },
    38: { name: "Tissemsilt", home: 600, desk: 350, desk_communes: ["Tissemsilt"], communes: ["Tissemsilt", "Theniet El Had", "Bordj Bounaama"] },
    39: { name: "El Oued", home: 800, desk: 450, desk_communes: ["El Oued"], communes: ["El Oued", "Guemar", "Robbah"] },
    40: { name: "Khenchela", home: 700, desk: 400, desk_communes: ["Khenchela"], communes: ["Khenchela", "Kais"] },
    41: { name: "Souk Ahras", home: 700, desk: 400, desk_communes: ["Souk Ahras"], communes: ["Souk Ahras", "Sedrata"] },
    42: { name: "Tipaza", home: 500, desk: 300, desk_communes: ["Tipaza", "Kolea"], communes: ["Tipaza", "Koléa", "Cherchell", "Hadjout", "Bou Ismail"] },
    43: { name: "Mila", home: 650, desk: 350, desk_communes: ["Mila", "Chelghoum Laïd"], communes: ["Mila", "Chelghoum Laïd", "Tadjenanet", "Ferdjioua"] },
    44: { name: "Aïn Defla", home: 550, desk: 300, desk_communes: ["Aïn Defla", "Khemis Miliana"], communes: ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf"] },
    45: { name: "Naâma", home: 750, desk: 450, desk_communes: ["Naâma", "Méchria"], communes: ["Naâma", "Aïn Sefra", "Méchria"] },
    46: { name: "Aïn Témouchent", home: 400, desk: 200, desk_communes: ["Aïn Témouchent", "Béni Saf"], communes: ["Aïn Témouchent", "Hammam Bou Hadjar", "Béni Saf", "El Malah"] },
    47: { name: "Ghardaïa", home: 750, desk: 450, desk_communes: ["Ghardaïa"], communes: ["Ghardaïa", "Metlili", "El Guerrara", "Berriane"] },
    48: { name: "Relizane", home: 450, desk: 250, desk_communes: ["Relizane"], communes: ["Relizane", "Oued Rhiou", "Mazouna", "Yellel"] },
    49: { name: "El M'Ghair", home: 800, desk: 450, desk_communes: ["El M'Ghair"], communes: ["El M'Ghair", "Djamaa"] },
    50: { name: "El Meniaa", home: 850, desk: 500, desk_communes: ["El Meniaa"], communes: ["El Meniaa"] },
    51: { name: "Ouled Djellal", home: 750, desk: 400, desk_communes: ["Ouled Djellal"], communes: ["Ouled Djellal", "Sidi Khaled"] },
    52: { name: "Bordj Baji Mokhtar", home: 1250, desk: 800, desk_communes: ["Bordj Baji Mokhtar"], communes: ["Bordj Baji Mokhtar"] },
    53: { name: "Béni Abbès", home: 900, desk: 550, desk_communes: ["Béni Abbès"], communes: ["Béni Abbès"] },
    54: { name: "Timimoun", home: 950, desk: 550, desk_communes: ["Timimoun"], communes: ["Timimoun"] },
    55: { name: "Touggourt", home: 800, desk: 450, desk_communes: ["Touggourt"], communes: ["Touggourt", "Temacine"] },
    56: { name: "Djanet", home: 1250, desk: 800, desk_communes: ["Djanet"], communes: ["Djanet"] },
    57: { name: "In Salah", home: 1050, desk: 650, desk_communes: ["In Salah"], communes: ["In Salah"] },
    58: { name: "In Guezzam", home: 1250, desk: 800, desk_communes: ["In Guezzam"], communes: ["In Guezzam"] }
};
